name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: arm64
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
